import testAdd from './add';
import testFibonacci from './fibonacci';
import testVariable from './variable';
import testUnary from './unary';
import testStr from './str';
import testSwitch from './switch';
import testClass from './class';
import testLinker from './linker';
import testBitcodeWriter from './bitcodeWriter';
import testIntrinsic from './intrinsic';
import testException from './exception';
import testType from './type';
import testDebugInfo from './debugInfo';
import testTarget from "./target";

testAdd();
testFibonacci();
testVariable();
testUnary();
testStr();
testSwitch();
testClass();
testLinker();
testBitcodeWriter();
testIntrinsic();
testException();
testType();
testDebugInfo();
testTarget();
